### ISSUE TITLE
Use IndexedDB for persistence

### ISSUE THREAD

**Issue by dslmeinte** [freon4dsl/Freon4dsl#295]
Instead of having to run a model server/backend, use the browser's built-in IndexedDB (more flexible than LocalStorage) for persistence, so the playground IDEs can be fully offline.

**Comment by joswarmer** [comment]
This is a nice idea, but there are too many more important things to work on for the foreseeable future.

**Comment by joswarmer** [comment]
Can't find the branch in Freon, but if you look at your own repositories there is a fork doing something with IndexDB.  
You clearly have too many repositories :-).

**Comment by dslmeinte** [comment]
Define “too many” 😃 

I'll resurrect this issue once I happen to have time to update that branch.
