### ISSUE TITLE
Server does not respond on Macbook 

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#325]
If on a macbook the server does not respond it may be due to a port conflict with the default port of 5000. If this is the error:

  Failed to load resource: the server responded with a status of 403 ()  chrome-error://chromewebdata/:1

This seems happen because of a conflict with /System/Library/CoreServices/ControlCenter.app/Contents/MacOS/ControlCenter which runs on port 5000. 

Switching the port by updating "start" command in package.json for the webapp in the playground to something like the following fixes the issue.

"start": "sirv public --port 8001"
 
Is there another reason this could be happening or a better way to fix it?

**Comment by dslmeinte** [comment]
I think port numbers in the 8000- are more familiar to devs, so I'd be in favor of using that range as well.

**Comment by joswarmer** [comment]
This is the right way to do this. @dslmeinte didn't realise that we could better use the 8000 range.

**Comment by joswarmer** [comment]
IS this resolved now?

**Comment by globallyunique** [comment]
Resolved by changing the port on the dev command. Perhaps it should be changed in the distribution and/or documentation so others don't have the issue.

**Comment by joswarmer** [comment]
Solved by changing default ports.
