### ISSUE TITLE
box: undefined undefined error

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#326]
I suddenly started getting NAN "NotTextBox" errors displayed in the browser. I thought it was something I'd done wrong so I started over. I cloned freon4dsl, installed the example app in the playground as described in the ReadMe and I get the same error. 
 
    Example > >  box: undefined undefined  > kind: undefined  > elem: undefined - undefined > (x, y): NAN "NotTextBox"

Could I have done something to my environment or has anything changed that could cause this?

**Comment by globallyunique** [comment]
I made a mistake and the Example model on a clean install works.

**Comment by joswarmer** [comment]
Will take a look together online.
