### ISSUE TITLE
Selecting and deleting a child element isn't easy

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#327]
A child that isn't part of a list requires two steps to delete:
- select the entire child
- use the 'delete' key rather than the backspace key

using the right key on a Mac isn't simple. 
knowing what and how to select the element to be deleted seems tricky.

**Comment by globallyunique** [comment]
I just discovered that option-cmd on a mac selects a child expression and then the delete key removes it. This helps make deleting a child easier. 

The delete is not reversible by undo. Is that a bug or a known limit?

**Comment by joswarmer** [comment]
This should work, so this qualifies as a bug.
