### ISSUE TITLE
adding a 0-9 digit to a binary expression doesn't work

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#328]
The implementation uses a regex to identify that when /0-9/ is entered that number should be added to the expression. Currently you can't just ender a digit, e.g., '1', you must enter '/1/'.

**Comment by globallyunique** [comment]
As an example of this or a related problem the 'Example' sample app allows entry of digits and strings but doesn't display the value entered until the view is changed.

**Comment by joswarmer** [comment]
This is about the custom action in the `Example` language.  The regular expression is ignored and handled as a regular string.
