### ISSUE TITLE
DocuProject does not install and run

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#331]
Installing the DocuProject sample model fails due to import failures in config/ProjectitConfiguration.tx that I didn't see how to fix. Is this an example that can be updated to work with the current version?

There are similar problems with the ExpressionLibrary and calculator samples. I was trying these to see a working example of expressions. Can a sample that shows interesting expressions be updated to work with the current version?

**Comment by joswarmer** [comment]
Ahh!  The `ProjectItConfiguration.ts` files are leftovers from the past and should be removed. I have updated the development branch accordingly, please update your project.
