### ISSUE TITLE
Number field default value of zero must be deleted to enter a number

### ISSUE THREAD

**Issue by globallyunique** [freon4dsl/Freon4dsl#335]
A number field displays with a default value of zero. To enter the desired value of the number the zero must usually be deleted, e.g., 

default is display as: '0'
want to enter a value of: '1'
type '1'
field contains '10'
must delete the '0'

I see that a digit is needed as a valid value for the field. Seems like special logic is needed for the first time the user enters the number field and if the value is zero it is deleted or a special empty indicator is shown, e.g., <number>, that is deleted when a digit is typed.

**Comment by joswarmer** [comment]
The problem is that we need to leave the number property in typescript initially `undefined`, and if the user does not change this, we need to take the possibility of being undefined into account where we (de)serialize the model. Need to check whether this is problematic in practice.

**Comment by joswarmer** [comment]
You can use the `deleteWhenEmpty` property of a textbox as shown in the example sample project in the custom projection.
The editor has been improved to not show `NaN`, but just being empty when there is no value available. I think this solves this issue.
